# Generated by Django 4.2 on 2023-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='location',
            field=models.CharField(default='none', max_length=50, unique=True),
        ),
    ]
