# Generated by Django 4.2 on 2023-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_attraction_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
