# Generated by Django 4.2 on 2023-04-14 07:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_user_home_town_user_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(default='none', max_length=50)),
                ('description', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('num_of_adults', models.IntegerField(default=0)),
                ('num_of_children', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='users/%Y/%m/')),
                ('name', models.CharField(default='none', max_length=100)),
                ('price_for_adults', models.FloatField(default=0)),
                ('price_for_children', models.FloatField(default=0)),
                ('departure_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.attraction')),
                ('customers', models.ManyToManyField(related_name='tours', through='tours.BookTour', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(related_name='tours', to='tours.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booktour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
        migrations.AddField(
            model_name='booktour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booktour',
            unique_together={('user', 'tour')},
        ),
    ]
