# Generated by Django 4.2 on 2023-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_attraction_location_alter_imagetour_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='location',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
