# Generated by Django 4.2 on 2023-04-14 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_bill_comment_rate_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
