# Generated by Django 4.2 on 2023-04-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tours.tour'),
        ),
    ]
