# Generated by Django 4.2 on 2023-04-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_imagetour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour'),
        ),
    ]
