# Generated by Django 4.2 on 2023-04-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_imagetour_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetour',
            options={'verbose_name': 'Image of tour'},
        ),
    ]
