# Generated by Django 4.2 on 2023-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_imagetour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='images/tours/%Y/%m/'),
        ),
    ]
