# Generated by Django 4.2 on 2023-04-19 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetour',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
