# Generated by Django 4.2 on 2023-04-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_remove_imagetour_description_imagetour_descriptions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktour',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
    ]
