# Generated by Django 4.2 on 2023-04-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_booktour_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tour')},
        ),
    ]
