# Generated by Django 4.2 on 2023-04-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'tour')},
        ),
    ]
