# Generated by Django 4.2 on 2023-05-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetour',
            options={},
        ),
        migrations.AlterField(
            model_name='imagetour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour'),
        ),
    ]
