# Generated by Django 4.2 on 2023-05-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0021_paymentmethod_bill_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='tour',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='tours.blog'),
        ),
    ]
