# Generated by Django 4.2 on 2023-05-02 14:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0022_remove_commentblog_tour_commentblog_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='blog',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/blogs/%Y/%m'),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_blog',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
